# Generated by Django 2.2.5 on 2019-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='gas',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
