# Generated by Django 2.2.5 on 2019-09-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190926_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='gas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='humidity',
            name='humidity',
            field=models.FloatField(),
        ),
    ]
